# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ACSNetworkingDemo' do

# pod 'ACSNetworking', :git => 'https://github.com/Hyosung/ACSNetworking.git', :tag => '0.0.1'
# pod 'ACSNetworking', :podspec => '../ACSNetworking.podspec'
pod 'ACSNetworking', :path => '../'
# pod 'ACSNetworking', :local => '../'

end

target 'ACSNetworkingDemoTests' do

end

